import { rect, pad, block } from '#game/routes/shapes';

const burn = (name, x, y, extra = {}) => ({name, x, y, w: 1.8, h: .9, ...extra});
const room = (x, y, w = 7, h = 3) => [rect(x, 0, w, y, 'brick'), rect(x, y + h, w, .4, 'roof'), rect(x + w - .35, y, .35, h, 'brick')];
const sealed = (x, y, w = 6, h = 3) => [...room(x, y, w, h), rect(x, y, .35, h, 'brick')];
function incident(spec) {
  const pools = spec.pools || [{x: 8, y: 2.25, bottom: .35, w: 4.5}];
  const rack = {x: 3, y: .9, w: 3.7};
  return {collection: 'Fire service', theme: 1, height: 24, cable: 3.6, start: 0, gold: 110, silver: 180, ...spec,
    fire: {fires: spec.fires, pools, headers: spec.headers || []},
    industry: {tool: spec.tool || 'hose', goal: 'fire', rack, output: {x: spec.width - 3, y: .9}},
    terrain: [rect(-12, -40, spec.width + 24, 40, 'earth'), block(3, .9, 4, 'metal'), block(spec.width - 3, .9, 3.5, 'metal'),
      ...pools.flatMap(p => [rect(p.x - p.w / 2, 0, p.w, p.bottom, 'metal'),
        rect(p.x - p.w / 2, p.bottom, .16, p.y - p.bottom, 'metal'), rect(p.x + p.w / 2 - .16, p.bottom, .16, p.y - p.bottom, 'metal')]),
      ...(spec.terrain || []), ...spec.fires.flatMap((f, i) => f.mobile ? [] : [{...rect(f.x, f.y, f.w, f.h, 'fuel'), fire: i}]),
      ...(spec.headers || []).flatMap(h => [rect(h.x - h.w / 2, h.y - .8, h.w, .12, 'metal'),
        rect(h.x - h.w / 2, h.y - .8, .12, .8, 'metal'), rect(h.x + h.w / 2 - .12, h.y - .8, .12, .8, 'metal')])],
    pads: [pad(3, .9, 'Tool rack', 3.7), pad(spec.width - 3, .9, 'Incident command', 3.3)],
    jobs: spec.fires.map(f => ({from: 0, to: 1, name: f.name}))};
}

export const fireRoutes = [
  incident({name: 'Mandatory training', sub: 'The pump has passed its exam. You have not.', width: 34,
    hint: 'Put out the two burning stacks. Hold J to spray, use I/K to aim, and L to turn the nozzle left or right.',
    tip: 'The nozzle aims relative to the swinging tool. Water takes time to arrive and the jet pushes back. Hover low over the blue basin with J released to refill.',
    fires: [burn('Training stack A', 18, 0), burn('Training stack B', 26, 0)]}),
  incident({name: 'Window of opportunity', sub: 'The insurance covers the building. Probably.', width: 36,
    hint: 'Feed the stream through the open left side of the burning workshop. Keep the rotors outside the roof.',
    tip: 'The roof stops water as well as aircraft. Fly beside the opening and aim a shallow stream inside.',
    terrain: room(19, 2, 10, 3.4), fires: [burn('Workshop bench', 25, 2)]}),
  incident({name: 'The other side of the fence', sub: 'The gate key is in the burning shed.', width: 38,
    hint: 'Arc the stream over the fence into the yard, then cool the higher stack.',
    tip: 'Water follows a falling arc. Raise the nozzle enough to clear the fence, then let gravity do the last part.',
    terrain: [rect(19, 0, .3, 3.4, 'metal'), block(29, 3.2, 4.5, 'brick')],
    fires: [burn('Fenced timber', 23, 0), burn('Raised timber', 28, 3.2)]}),
  incident({name: 'The bucket list', sub: 'Same bucket. A much better liquid.', width: 37, tool: 'ladle', gold: 150, silver: 230,
    hint: 'Dip the bucket in the blue basin, lift it over the timber beds and hold J to pour right. U swaps tools while resting on the Tool rack.',
    tip: 'The old metalworking bucket holds real moving water. Fly smoothly to keep it aboard. A full dump covers more ground than a narrow stream.',
    terrain: [block(23, 1.5, 10, 'metal')],
    fires: [burn('Left timber bed', 18.5, 1.5), burn('Middle timber bed', 21.8, 1.5), burn('Right timber bed', 25.1, 1.5)]}),
  incident({name: 'Both ends of the street', sub: 'Every direction is the wrong direction.', width: 46, gold: 155, silver: 235,
    hint: 'Two sheltered stores open into the central alley. Turn the nozzle to reach both interiors.',
    tip: 'L turns the nozzle; I/K still raise and lower its aim. Recoil reverses too, so ease off before changing sides.',
    pools: [{x: 22, y: 2.25, bottom: .35, w: 4.5}],
    terrain: [rect(9, 0, 7, 1.2, 'brick'), rect(9, 1.2, .35, 3.6, 'brick'), rect(9, 4.8, 7, .4, 'roof'), ...room(29, 1.2, 8, 3.6)],
    fires: [burn('West store', 10.5, 1.2), burn('East store', 34, 1.2)]}),
  incident({name: 'The warm way up', sub: 'Your lift is also the problem.', width: 41,
    hint: 'Cool the tall timber stack and the roof fire. Their hot air pushes the rig upward until you extinguish it.',
    tip: 'Watch your height as a plume fades. A long spray changes the air supporting you as well as pushing the nozzle backward.',
    terrain: [block(22, 4, 5, 'brick'), block(31, 7, 5, 'brick')],
    fires: [burn('Drying stack', 21, 4, {plume: 34}), burn('Roof stock', 30, 7, {plume: 28})]}),
  incident({name: 'Unscheduled delivery', sub: 'The cargo would like to leave the incident.', width: 45, gold: 145, silver: 230,
    hint: 'Put out the burning wheeled crate. Your stream pushes it along the yard; follow it or drive it against a wheel stop.',
    tip: 'The crate has its own mass and rotation. Water transfers momentum to it, so aiming and moving the target are the same action.',
    terrain: [rect(16, 0, .5, .22, 'metal'), rect(35, 0, .5, .22, 'metal')],
    fires: [burn('Runaway crate', 23, .1, {mobile: true}), burn('Loading pile', 38, 0)]}),
  incident({name: 'Under the eaves', sub: 'A roof on top. A roof underneath.', width: 46, gold: 165, silver: 250,
    hint: 'Attack two sheltered fires at different heights. Move around the stepped roofs to find a clear line for the stream.',
    tip: 'Water cannot pass through a roof. Stop spraying while you reposition; the tank is lighter after use and fills at either basin.',
    pools: [{x: 8, y: 2.25, bottom: .35, w: 4.5}, {x: 37, y: 2.25, bottom: .35, w: 4.5}],
    terrain: [...room(18, 1.2, 8, 3), ...room(26, 6, 8, 3)],
    fires: [burn('Lower workshop', 22, 1.2), burn('Upper workshop', 30, 6)]}),
  incident({name: 'Nobody told the sprinklers', sub: 'A complete system, missing only the water.', width: 44, tool: 'ladle', gold: 175, silver: 260,
    hint: 'Fill the rooftop header with bucket water. Its pipe feeds the sprinklers inside the sealed storeroom. Cool the outside stack too.',
    tip: 'Every drop in the header becomes sprinkler water. Pour into its open top; overflow spills. The blue pipes show which room it serves.',
    terrain: sealed(24, 1.2, 9, 3.6),
    headers: [{x: 28.5, y: 6, w: 3.4, outlets: [{x: 27.7, y: 4.2}, {x: 30.2, y: 4.2}]}],
    fires: [burn('Sealed stock A', 26.8, 1.2), burn('Sealed stock B', 29.3, 1.2), burn('Outside stock', 17, 0)]}),
  incident({name: 'The neighbour’s shed', sub: 'The neighbours are watching.', width: 41, gold: 145, silver: 220,
    hint: 'Stop the fire spreading along three timber stacks. Water on the next stack buys time to finish the burning one.',
    tip: 'Wet fuel resists spread. Nearby hot stacks can reignite a dry one, so check every heat bar before leaving.',
    terrain: [block(25, 1.2, 12, 'metal')],
    fires: [burn('Original fire', 20, 1.2, {spreadFrom: [1]}), burn('Neighbour’s stock', 24, 1.2, {heat: .18, spreadFrom: [0, 2]}),
      burn('Last dry stack', 28, 1.2, {heat: .04, spreadFrom: [1]})]}),
  incident({name: 'Water goes somewhere', sub: 'Gravity has offered to help.', width: 46, tool: 'ladle', gold: 190, silver: 280,
    hint: 'Use the bucket on the upper timber, then work down the terraces. Spilled water keeps falling and can reach the lower fires.',
    tip: 'Water striking a plain roof runs along it before falling from the edge. Burning fuel absorbs water; cold surfaces let it run off.',
    terrain: [block(20, 6, 5, 'brick'), block(26, 3.4, 5, 'brick'), block(32, 1.2, 5, 'brick')],
    fires: [burn('Upper terrace', 19.3, 6), burn('Middle terrace', 25.3, 3.4), burn('Lower terrace', 31.3, 1.2)]}),
  incident({name: 'All available appliances', sub: 'One aircraft counts as all of them.', width: 61, gold: 310, silver: 460,
    hint: 'Supply the enclosed mill’s sprinklers, extinguish the rolling cargo and cool the roof stacks. Choose when to use the bucket and hose.',
    tip: 'The header keeps working while you fight elsewhere. Plan your refills and tool changes; cooling the high fire removes its updraft.',
    pools: [{x: 8, y: 2.25, bottom: .35, w: 4.5}, {x: 46, y: 2.25, bottom: .35, w: 4.5}],
    terrain: [...sealed(25, 1.2, 9, 3.6), block(39, 6.5, 5, 'brick'), rect(17, 0, .4, .22, 'metal'), rect(24, 0, .4, .22, 'metal')],
    headers: [{x: 29.5, y: 6, w: 3.4, outlets: [{x: 28, y: 4.2}, {x: 31, y: 4.2}]}],
    fires: [burn('Mill room A', 27.1, 1.2), burn('Mill room B', 30.1, 1.2), burn('Rolling consignment', 20, .1, {mobile: true}),
      burn('Mill roof', 38.2, 6.5, {plume: 28}), burn('East timber', 51, 0)]})
];
